### ISSUE TITLE
Allure report- in Email?

### ISSUE THREAD

**Issue by shahmit** [allure-framework/allure2#1093]
Hi Team,
Great work, it is such an awesome report!

Just wondering if there is .html file which can be used to add to the Jenkins Email Ext plugin, so that after the Jenkins build completion, it also sends the report in the email to the desired recipients.
Could you please let me know how to achieve this?
Any help here is much appreciated.
 Thanks again for a very cool report!

**Comment by fescobar** [comment]
https://github.com/allure-framework/allure2/issues/755#issuecomment-521385934

**Comment by shahmit** [comment]
Sorry, not following, how do i use this template in the Email Extension plugin in Jenkins.
Typically would call the email template like the attached-

**Comment by fescobar** [comment]
The allure docker container is different app, not related with this one. The allure for jenkins doesn’t provide any static email for sending by email. You could zip the entire allure-report folder and the send it compressed, but the person who open that report locally in his machine could not open the report because he will need a server to see it.

**Comment by shahmit** [comment]
Thank you for the response. Unzipping the folder does not work when sending to different stakeholders, is there any plan to auto generate a .html file?
There is a mail.html file in the export folder, however that is a blank file.

Regards,
Mitali

**Comment by fescobar** [comment]
That feature was requested a long time ago and I don’t think will be developed.
