### ISSUE TITLE
ubuntu 18.04 zsh: command not found: allure

### ISSUE THREAD

**Issue by moluoyu** [allure-framework/allure2#1114]
i installed allure following the steps:

![image](https://user-images.githubusercontent.com/27038644/88470541-2edf7e00-cf30-11ea-9375-06478726d19e.png)
Execute allure --version in console ,it can't find the command:

![image](https://user-images.githubusercontent.com/27038644/88470819-e88c1e00-cf33-11ea-93b4-f049fddb317d.png)

my zsh version:
![image](https://user-images.githubusercontent.com/27038644/88470830-0eb1be00-cf34-11ea-858f-eb443980b742.png)

**Comment by thuibr** [comment]
I have an insight in #989

**Comment by clarabez** [comment]
Proceed with [Manual Installation](https://docs.qameta.io/allure/#_manual_installation) as described on main page for Allure documentation.

Basically:

- Download Allure from maven repository;
- Unzip it;
- Copy path location for /bin;
- Add /bin location into your bash_profile or bashrc file;
- Source bash_profile or bashrc file;

Should work.

**Comment by martinstajnko** [comment]
> Proceed with [Manual Installation](https://docs.qameta.io/allure/#_manual_installation) as described on main page for Allure documentation.
> 
> Basically:
> 
>     * Download Allure from maven repository;
> 
>     * Unzip it;
> 
>     * Copy path location for /bin;
> 
>     * Add /bin location into your bash_profile or bashrc file;
> 
>     * Source bash_profile or bashrc file;
> 
> 
> Should work.

After that, I got: 
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

I installed Java. 
 
Now I am getting: 
Error: Could not find or load main class io.qameta.allure.CommandLine
Caused by: java.lang.ClassNotFoundException: io.qameta.allure.CommandLine

Can someone guide me through proper set up of Allure Test Report Framework? 
Has someone experience on how to set up Allure inside of Poetry environment? 

Thank you!

**Comment by karpikpl** [comment]
was this ever solved?
