### ISSUE TITLE
Fixtures order in 'Set up' report is inconsistent

### ISSUE THREAD

**Issue by Denis-Alexeev** [allure-framework/allure2#1156]
**Describe the bug**
Fixtures order in 'Set up' and 'Tear down' reports is inconsistent. Incorrect order even is illustrated in screenshot in allure API doc https://docs.qameta.io/allure/#_fixtures_and_finalizers

**To Reproduce**
1. Execute any test with session, module, class and function scope fixtures

**Expected behavior**
The fixtures' order in 'Set up' report is:
session_scope_fixture
module_scope_fixture
class_scope_fixture
function_scope_fixture

In 'Tear down' report is:
function_scope_fixture
class_scope_fixture
module_scope_fixture
session_scope_fixture

**Screenshots**
https://docs.qameta.io/allure/images/pytest_skoped_finalizers.png

**Environment (please complete the following information):**

| Allure version | 2.9.0 |
| --- | --- |
| Test framework | pytest |
| Allure adaptor | allure-pytest |
| Generate report using | allure generate path/to/dir |

**Comment by e7506c** [comment]
I see the same issue. Could you guys address this please?

**Comment by dmgant** [comment]
I also came across this, I have found that the order is dictated in alphabetical order by the -container.json files generated when running pytest. You can modify the names of the files by using a Pytest that hooks AllureFileLogger, however, you still need to handle this in Javascript or Java. 

My solution involved modifying the order of the array in the Javascript file before it is displayed, so that the teardown is in reverse order to the setup (by design in pytest). There does not seem to be an easy solution, as the order on which the fixtures were executed is not stored in the container files.

I am not sharing this solution because it looks hacky, but hopefully someone more experienced in Javascript or Java can come up with a proper solution.

**Comment by ShurikMen** [comment]
Maybe a solution from #1270 will do.

**Comment by dmgant** [comment]
> Maybe a solution from #1270 will do.

I do not think it is that easy unfortunately.

Considering you are using function scope fixture, In the AllureFileLogger, it is possible to hook the report_container function, this function will trigger for fixtures and for parameters in parametrized tests. The first call to this function that is not a parametrized test (a test result container with no children), will be the fixture that executed last in the setup, and first in the teardown, from here, you can figure out the order and add an extra element to the JSON that Java can process to generate the final JSON files. This way, you do not have to depend on the times (which by the way, might be the same for fixtures that execute fast enough).

However, if an exception is raised at some point after the teardown is registered, Allure Pytest plugin will forget to release this fixture internally and the next test will report it as if it was part of that test, the relevant JSON container will have the UUIDs of two tests which is wrong. A fixture with a function scope will only have one possible children so as a workaround you can remove the children's that were added last and just keep the first one.

It gets more complicated when you start mixing non-function scopes and exceptions in the setup or teardowns, this is hard to explain from the top of my head, I think there is no trivial solution that doesn't involve changing the allure2 pytest plugin.
