### ISSUE TITLE
Nested describes are hidden in Allure report

### ISSUE THREAD

**Issue by dmrnz** [allure-framework/allure2#1902]
**Is your feature request related to a problem? Please describe.**
Hi, I'm writing jest tests with six nested describes, and in the report there are only four upper ones visible, and then there are the list of test cases.

**Describe the solution you'd like**
Is there a way to increase the visibility level of describes in report, I would like to increase that number.

**Additional context**
![image](https://user-images.githubusercontent.com/43438823/213998382-93fa4ac3-7b11-4291-aaab-9a7c1391e95d.png)

**Comment by baev** [comment]
Currently, Allure Report only support up to 3 groups -- `parentSuite`, `suite`, `subSuite` (same for bdd: `epic`, `feature`, `story`). 

In order to deal with more nested describes, we join all the rest of the describes into a single label. See https://github.com/allure-framework/allure-js/blob/master/packages/allure-mocha/src/AllureReporter.ts#L114-L129 as an example
