### ISSUE TITLE
How to create and configure a custom  plugin?

### ISSUE THREAD

**Issue by guiyomh** [allure-framework/allure2#1938]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/allure-framework/allure-docs/) and submit a pull request

**Describe the improvement**

I'd like to report
- [x] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**

I'm looking to create an allure plugin to send a slack message with the link to the report and a brief summary of the results. But I don't understand anything in the documentation. And on google I find examples that seem to be from version 1. I'm not a java expert and I'm a bit lost. I would like to have a documentation like `how to create a plugin`.

- for example I don't know if I should make a fork of the allure2 project and submit a PR? or if I can make a standalone plugin?
- I don't know how to test my plugin locally. Should I add a `-plugins` parameter to the command line? or use a config file ?
- I am looking for how to write the configuration file but I can't find anything in the documentation.

Can someone help me to create my first plugin that for example sends a slack notification with the number of successful tests and the number of tests in error. Once I figure it out, I can do a PR on the documentation.

thx

**Comment by MohabMohie** [comment]
same concern

**Comment by baev** [comment]
As for today, the easiest way is to maintain a custom fork of the allure2 repository or create a separate tool that relies on `allure-report` folder contents (like `summary.json`) to do the notifications.

The main deal with the plugins is that they were planned as something bigger, but they were never fully supported by the ecosystem, e.g., there is no way to add a plugin when using the Allure Jenkins Plugin.

So, even if you manage to create a proper plugin, you'll still need to include it into `allure-comamndline.zip` somehow to install the desired CI.

Meanwhile, Allure 3 is already in development and planned for this year. It will include a Slack notifications feature and introduce more possibilities for extending and customising the reports. Feel free to subscribe to the waiting list: https://allurereport.org/allure-report-3.0/

**Comment by baev** [comment]
@dutyfree123123123 yes, it is planned. 

Unfortunately, the page didn't make it through the site migration to VitePress, and we don't feel like spending time recovering it. It was a simple subscription form; you can use the one in the footer instead.

The current state of Allure 3 is that the core is mainly done, and we are finishing the final tasks we'd like to complete before we open-source the code. Please don't expect GA release this year since many different things are planned, and due to the vast Allure ecosystem, the implementation may take a while. 

And the bonus: here is a screenshot of the new report (one of the many) called Allure Awesome: 

<img width="968" alt="Screenshot 2024-11-14 at 14 36 07" src="https://github.com/user-attachments/assets/d09eb8a8-6a55-4729-a0ad-0f0c5c47e486">
