### ISSUE TITLE
Allure Report: Ability to change default order of TestNG DataProvider cases

### ISSUE THREAD

**Issue by ravxz** [allure-framework/allure2#2201]
### Describe the Bug

There is no option to set default order of test cases in Allure 2 report.

### Steps to Reproduce

1. Create any TestNG test class with @dataProvider and @test methods. E.g.:
```
public class DataProviderTest {

    @DataProvider
    public Object[][] args() {
        return new String[][]{{"One"},{"Two"},{"Three"},{"Four"},{"Five"}};
    }

    @Test(dataProvider = "args")
    public void test(String arg) {
        System.out.println(arg);
    }
}

```
2. Run tests with Allure 2 enabled.
3. Generate Alllure 2 report.
4. Open report and look at cases default order (for parameters): Five, Four, One, Three, Two.

### Expected Behaviour

Cases order should correspond to run order: One, Two, Three, Four, Five.

### What Language are you using?

Java

### What Framework/Allure Integration you are using?

testng@6.10, allure@2.19.0

### What version of Allure Integration you are using?

2.19.0

### What version of Allure Report you are using?

2.19.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment]
You can sort tests by order in the report. Please note that it will sort test results by the start timestamp, which means that the order of the test results is not guaranteed to match the order of the parameters for some parallel run configurations (when each parameter value runs in parallel) but represents the actual execution order. Also, since it uses timestamps in milliseconds, super-fast tests may have the same start time, in which case the order is not guaranteed.
