### ISSUE TITLE
Attachments with type "text/html" downloaded in '.txt' format.

### ISSUE THREAD

**Issue by besimp** [allure-framework/allure2#516]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Attachments with type "text/html" downloaded in '.txt' format.

#### What is the expected behavior?
Attachments with type "text/html" should be downloaded in '.html' format.

#### Please tell us about your environment:

| Allure version | 2.3 |
| --- | --- |
| Test framework | any |
| Allure adaptor | any |
| Generate report using | any |

**Comment by alexander-kotlyar** [comment]
Still actual? Because as i see for now: html/xhtml files downloads for type "text/html".

**Comment by wesmcouch** [comment]
Steps to reproduce:
1. Allure.addAttachment("htmlAttachment", "text/html", "randomContent");
2. Generate report
3. Attachment ends with .txt instead of html

Workaround - specify extension
1. Allure.addAttachment("htmlAttachment", "text/html", "randomContent", "html");
2. Generate report
3. Attachment ends with .html and opens correctly

**Comment by besimp** [comment]
If use annotation @Attachment(value = "HTML attachment", type = "text/html") - all works fine
If use Allure.addAttachment("Test title", "text/html", htmlString); - attachment saved as txt

**Comment by wesmcouch** [comment]
@besimp a workaround there is to specify the fileExtension as the fourth parameter.

**Comment by Vishnu-2810** [comment]
How to add a custom HTML table in attachment?
