### ISSUE TITLE
Expand/Mark failed `Setup` 

### ISSUE THREAD

**Issue by dimkin-eu** [allure-framework/allure2#547]
#### I'm submitting a ... 
  - [x] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
If test fails on prepare, you will know this if you will expand `Setup` section
For sure, same could be nice to have for `Tear down`

#### What is the expected behavior?

- mark `>` red

or

- expand section if fail inside

#### What is the motivation / use case for changing the behavior?
Better understanding, where fail happened

#### Please tell us about your environment:

| Allure version | 2.3.1 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.0-BETA16 |
| Generate report using | allure-maven@2.18 |

#### Other information 
![image](https://user-images.githubusercontent.com/7899764/29174512-3aa26986-7def-11e7-8342-27edaca2e2e8.png)

**Comment by slipwalker** [comment]
It's quite unclear when there are being tests failures on set up or tear down stages. In order to get it, you need to expand tests and then look for failed setup or tear down. It's a bit inconvenient and really annoying. Allure report Suites level knows nothing about such failures. What I mean, exactly shown on pictures:

Allure report Suites with no failures indicated:
<img width="1332" alt="suites" src="https://user-images.githubusercontent.com/720677/45542800-91876f00-b81b-11e8-9357-4605459c746a.png">


But there are some failures happened on tear down stages:
<img width="614" alt="failures_on_tear_down_stages" src="https://user-images.githubusercontent.com/720677/45542903-df03dc00-b81b-11e8-9b7f-20790c59d24a.png">

It's a bit confusing when you look at the green Allure report that in fact has failed stages there. The same is valid for set up stage as well. 
@baev could you please fix this in upcoming release/s to get it more readable? Thanks in advance.
