### ISSUE TITLE
Remove attachments for successful tests

### ISSUE THREAD

**Issue by ekonkov** [allure-framework/allure2#569]
Allure 1 has an important feature - if there is a property ```allure.report.remove.attachments``` set than attachments with names matched by its value as regex will be removed for successful tests.

As far as I understand there is no equivalent in Allure 2.

Is there a possibility or plan to implement this feature in Allure 2?

**Comment by gladnik** [comment]
This feature will be added in future. As a temporary workaround use this: https://gist.github.com/gladnik/99793dbaa29dd3b8feef909de7639fc3

**Comment by cookieMr** [comment]
It's almost 2y old issue.

Is there a reason for which this feature is not implemented (yet)? if so, can you share that reason? If not, i am just bringing this issue to your attention ;)

**Comment by baev** [comment]
> Is there a reason for which this feature is not implemented (yet)? if so, can you share that reason?

because there is not many users are asking for such feature. And you can use our API to remove attachments from passed tests (as @gladnik suggested)

At the moment we are working towards realtime reports (Allure Enterprise already has support of realtime reports), so you'll get attachments processed before test finishes

BTW there is still a need of such feature even for real-time reports (it slows down results processing in case of thousands of attachments per test) but implementing this feature in this case requires a bit more work

**Comment by cookieMr** [comment]
> > Is there a reason for which this feature is not implemented (yet)? if so, can you share that reason?
> 
> because there is not many users are asking for such feature. And you can use our API to remove attachments from passed tests (as @gladnik suggested)
> 
> At the moment we are working towards realtime reports (Allure Enterprise already has support of realtime reports), so you'll get attachments processed before test finishes
> 
> BTW there is still a need of such feature even for real-time reports (it slows down results processing in case of thousands of attachments per test) but implementing this feature in this case requires a bit more work

thx for the explanation :) keep up the good work

**Comment by VladimirPodolyan** [comment]
Up

**Comment by joycezhaomeng** [comment]
up
