### ISSUE TITLE
Attachments are generated and placed into allure-results folder but not attached to report (data/attachments folder is empty in test-report folder)

### ISSUE THREAD

**Issue by tlytvyn** [allure-framework/allure2#654]
This is very strange issue. I've beed using Allure 1.X and Allure 2.X for a while and never seen that before. But the most strange thing is that sometimes attachments are attached correctly and sometimes they are not. I've spent lots of times to figure out and to find the reason (like regularity) but without success. 

**Libraries used:**
Maven plugin 2.9 is used.
allure-testng library 2.0-BETA19
testng 6.11
surefire plugin 2.20
aspect4j 1.8.12 (also tried 1.8.10)

**Use case**
I have this method:
`@Override
    public void onTestFailure(ITestResult arg0) {
        Allure.addAttachment("Screenshot after failed test", "image/png", getScreenshotByteIS(), "png");
        Allure.addAttachment("Failed page source", "text/plain", getFailedPageSource(), "txt");
    }`

I also tried to use simple old style @Attachment - result is the same.

**Problem**
I can see attachment files added in allure-results folder with .png and .txt extensions and open them normally, but they are not attached to report sometimes after mvn allure:report. 
I don't have any exact steps. Maybe some suggestions how to see some logs why are files not being attached properly?
I have attached allure-results folder, so maybe someone can try to generate report from it using maven plugin and take a look what's wrong.
[allure-report-results.zip](https://github.com/allure-framework/allure2/files/1427680/allure-report-results.zip)
![screen shot 2017-10-30 at 3 19 13 pm](https://user-images.githubusercontent.com/2183790/32178097-94a27dec-bd94-11e7-9c4e-1937c428d469.png)
![screen shot 2017-10-30 at 4 58 37 pm](https://user-images.githubusercontent.com/2183790/32178098-94cff024-bd94-11e7-80d6-c3d52b8dc083.png)
![screen shot 2017-10-30 at 4 58 57 pm](https://user-images.githubusercontent.com/2183790/32178100-9502d00c-bd94-11e7-8977-4956c7e8499e.png)

**Comment by sskorol** [comment]
@tlytvyn the root cause could be in TestNG itself, which doesn't guarantee listeners execution order. So theoretically sometimes Allure listener may finalize test results before your "taking screenshot event" occurs.

You can try moving screenshot taking feature from `onTestFailure` to `afterInvocation` to make sure that it'll be executed before test results' finalization.

**Comment by tlytvyn** [comment]
@sskorol Looks like IInvokationListener listener fixed the issue.
Just want to clarify: Attachments files are added to allure-result folder but not attached to report after mvn allure:report command is being executed. Is this because attachment's files were added somehow with "incorrect" flags to results dir because of listener issue and Allure is not picking them during report generation?

**Comment by sskorol** [comment]
@tlytvyn tests' closure activities occur in `onTestFailure` and other similar methods in Allure TestNG listener. This step also includes test results writing event. 

When you called attachment API, files were physically generated. But test results have already been written before (due to unpredictable listeners order).

Besides that, I don't see any attachment nodes in *-result.json files. So it confirms my assumption that results were written before actual screenshots taking.

**Comment by tlytvyn** [comment]
@sskorol yeah, that's make sense, seems like because of listener ordering issue, they were generated but not linked in aggregation results .json file properly. Thanks
