### ISSUE TITLE
How to Embbed Test Case Video In Allure Jenkins Plugin

### ISSUE THREAD

**Issue by anuvratashu** [allure-framework/allure2#759]
Hey,
I was trying various ways to embed a test run video in Allure Report plugin with Protractor.
we can do it if we add a video Folder inside the Allure Report folder and add the video path in the allure description . So then Allure displays and play the video in description part.

However, i wanted to achieve the same using the Allure Jenkins plugin. Can you please let me know if there is any way to embed and play the video in allure report generated using allure jenkins plugin.

I saw the Video on you tube where they are running video inside the Allure report in jenkins. But not sure how they have setup. Please help?
https://www.youtube.com/watch?v=74zD5q9DKTw

**Comment by baev** [comment]
At the moment Allure supports 3 different video formats: `video/mp4`, `video/ogg`, `video/webm`. In order to have video in the report attach it the same way you attach other files (for example, using `@Attachment` method) and specify one of content types I mentioned above

**Comment by sumeetpanjabi** [comment]
Do you have any example for implementation in Java?

**Comment by fescobar** [comment]
@sumeetpanjabi 
Java Implementation:
https://github.com/fescobar/allure-docker-service/tree/master/allure-docker-java-cucumber-jvm-example
https://github.com/fescobar/allure-docker-service/tree/master/allure-docker-java-testng-example

More examples:
https://github.com/fescobar/allure-docker-service#generate-allure-results

**Comment by sumeetpanjabi** [comment]
Thanks @fescobar . Any utility are you aware of to record screen video in mp4 format.

**Comment by fescobar** [comment]
Selenoid and Zalenium are customized Selenium Grid. They record videos mp4 for you.
But if you want to record your own video, try with this http://www.experimentalqa.com/2017/11/record-selenium-test-video-in-mp4.html?m=1

**Comment by autTestUser** [comment]
@anuvratashu you said **"we can do it if we add a video Folder inside the Allure Report folder and add the video path in the allure description . So then Allure displays and play the video in description part."**

The video is not available now in that youtube link you mentioned. Do you have a sample code? Could you please share it?

**Comment by sergiu-mezei-aera** [comment]
@fescobar I'm trying to add a html <video> tag inside the Allure report that has the source pointing to a AWS S3 URL that contains the browser session recording. Since this recording is only available after the browser session closes, cannot stream it inside the TestNG TestListener - onTestFailure() to attach it as video/mp4 because it doesn't exist yet. 

I've tried attaching a html code snippet (as shown [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video)) as 'text/html' but it shows up as a text attachment, not processing the html code.

Using this version of Allure:
'io.qameta.allure:allure-testng:2.19.+'

 How can I achieve something like this?
