### ISSUE TITLE
Results are generated only for one Example using Scenario Outline in Allure report 

### ISSUE THREAD

**Issue by radclive** [allure-framework/allure2#762]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)
I have one scenario outline with one example table. Inside the example table, I have A and B.
Once I execute the scenario outline, it will generates two testsuites inside the allure-results folder. 
One testsuite is for A and another one is for B.

![image](https://user-images.githubusercontent.com/37093784/37331704-9912c6fc-26df-11e8-8c8e-e8f8e9600bdf.png)

However, inside the allure report. It only display the report for A and not for B. It should however display both A and B.

![image](https://user-images.githubusercontent.com/37093784/37334556-336acf86-26e7-11e8-8352-4385f7b1f905.png)

| Allure version | 2.6.0 |
| --- | --- |
| Test framework | junit@4.12 |
| Allure adaptor | allure-cucumber-jvm-adaptor@1.6.1 |
| Generate report using | allure-maven-plugin@2.5 |

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by anditpl** [comment]
I have the same problem.

When I use this step twice:

$ behave -f allure_behave.formatter:AllureFormatter -o %allure_result_folder% ./features 

And then $ allure serve %allure_result_folder%
There is always 1 test case How can I manage to sum test cases? I want to see test cases.

I've run also this code twice:

behave -f allure_behave.formatter:AllureFormatter -o results ./features 
and then:
allure generate results/ -o report/

But still, I get only 1 test case.

I want to see for example similar outcome [https://i.stack.imgur.com/H1eig.png](url)

**Comment by stephenmwilliams** [comment]
Hi, I'm a new user of Allure reports and so firstly, thanks to the development team for sharing their time and effort to give this to the community. 

I'm also experiencing the same behavior in .NET using NUnit and SpecFlow. When a scenario outline is used only a single test is presented in the report. Multiple iterations which are run due to having multiple rows of Examples, are not displayed in the report individually.

Versions:
- Specflow Allure - 2.2.0.11
- Allure commons - 2.2.0.7
- NUnit - 3.9.0
- NUnit3TestAdapter - 3.9.0

When looking at the Allure report JSON files which are created, the test name is the scenario name, not the fully qualified test name that you can also see in the NUnit XML. i.e. it does not include parameters from the examples tables. This means that to the allure report generator it's the same test case that has been run multiple times.

The code in Allure which is responsible for setting the test name appears to be in the file https://github.com/allure-framework/allure-csharp/blob/master/Allure.SpecFlowPlugin/AllureHelper.cs
method StartTestCase
```c#
internal static TestResult StartTestCase(string containerId, FeatureContext featureContext,
            ScenarioContext scenarioContext)
        {
            var featureInfo = featureContext?.FeatureInfo ?? emptyFeatureInfo;
            var scenarioInfo = scenarioContext?.ScenarioInfo ?? emptyScenarioInfo;
            var tags = GetTags(featureInfo, scenarioInfo);
            var testResult = new TestResult
            {
                uuid = NewId(),
                historyId = scenarioInfo.Title,
                name = scenarioInfo.Title,
                fullName = scenarioInfo.Title,
                labels = new List<Label>
                    {
                        Label.Thread(),
                        Label.Host(),
                        Label.Feature(featureInfo.Title)
                    }
                    .Union(tags.Item1).ToList(),
                links = tags.Item2
            };
```
As you can see, this is setting the name of the test case to be whatever SpecFlow has set scenarioInfo.Title to be. Which is at the moment, just the scenario name and doesn't consider any of the Attributes which SpecFlow NUnit cs generator includes in the code behind files.

In C# I'm just working around this at the moment by changing the value of the Allure.Commons TestResult name in run time to something more meaningful. In my case, all the examples tables include a first column which is a description of that data set, so therefore I append that on to the test name E.g. appending on an argument from the test examples table

```c#
if (scenarioContext.ContainsKey("Allure.Commons.TestResult"))
{
      TestResult tr = (TestResult) scenarioContext["Allure.Commons.TestResult"];
      tr.name = scenarioContext.ScenarioInfo.Title + ": TestCase: " + NUnit.Framework.TestContext.CurrentContext.Test.Arguments[0];
}
```

**Comment by radclive** [comment]
I somehow solve my problem by updating the public maven repo to the latest version.

**Comment by PavanGurramQA** [comment]
Has anyone got a solution for this issue?  I'm using Allure reporting with WebdriverIO, Nodejs and NPM. Struggling to get all the executed steps of Scenario Outline in the report. As of now, the report doesn't show right count of the executed steps of Scenario Outline. Any help would be really appreciated!!

**Comment by PavanGurramQA** [comment]
Hi All,

I've resolved it by passing a parameter to scenario outline title so that Allure treats it as a different test case. Thanks.

**Comment by baev** [comment]
fixed in latest allure-cucumberjvm releases
