### ISSUE TITLE
Question: How does allure generate html from json?

### ISSUE THREAD

**Issue by EltonZhong** [allure-framework/allure2#860]
Recently I'm writing logic to generate allure .json file on my own.
So there are my questions:
1. Is container.json needless? I find that everything stays the same even if I delete all container json files.
2. Where can I get a document for which filed of JSON file is rendering? Tired to retry again and again.

Thank you very much!

**Comment by baev** [comment]
>  Is container.json needless? I find that everything stays the same even if I delete all container json files.

Containers are only used to provide information about test fixtures (set up and tear down methods). In order to link test result with container you need to set add its `uuid` to `children` of container. Also containers can have other containers as children as well. 

I think this logic is too complicated so I am planing to make some changes on this in next major release. BTW no ETA at the moment

> Where can I get a document for which filed of JSON file is rendering? Tired to retry again and again.
 
At the moment there is no documentation or schema for our results format. And yes, it would be so nice to have it, but our team literally have no time for that.

Please use our Gitter chats for questions https://gitter.im/allure-framework/allure-core

For all the schema related questions feel free to DM me

**Comment by EltonZhong** [comment]
Thanks, very helpful :) 👍
