### ISSUE TITLE
do you publish this allure to Maven repository?

### ISSUE THREAD

**Issue by rameshnatesan** [allure-framework/allure2#969]
Can you publish this allure2 to Maven repository? Also, I find it confusing to have two different products qameta and yandex which offer Allure. Are these separate companies or they are the same?

**Comment by baev** [comment]
All Allure 2 artifacts are published to maven repository. What module are you missing?

Allure was originally created by Yandex team. Since version 2 the project moved to separated company called Qameta Software. So the old artifacts are under yandex namespace, the new one are using qameta namespace

**Comment by EasyZeng2018** [comment]
do we publish allure-generator to maven repository? How we use this generator as I found no readme.md in the allure-generator project.

Thanks for the plugin.
