### ISSUE TITLE
Allure hangs or spends hours to generate report in case of huge number of tests(~70K)

### ISSUE THREAD

**Issue by SergeyChu** [allure-framework/allure2#970]
Using allure 2.8.1 under Ubuntu 16.04.3 LTS (Xenial Xerus) with python 3.6.
And we noticed that when number of iterations is ~70K  Allure hangs upon generation of the report(after pytest finishes execution), if we wait for about 5-7 hours it finishes the generation.
But the amount of time is definitely unacceptable

It might be related to huge number of small files in generatedReport folder( categories.json )
But even read each from ~70K small files shouldn't take so long.

Using the following options to launch allure and pytest accordingly:
`/allure/bin/allure generate --clean ./generatedReport/ --output $allure_report`
`pytest -n $threads --alluredir=generatedReport -v --tb=line --continue-on-collection-errors --disable-warnings --cache-clear --durations=5 --clean-alluredir --allure-no-capture`

I've also found similar complain on stackoverflow:
https://stackoverflow.com/questions/45712514/allure-report-generation-and-display-speed-in-case-of-large-amount-of-tests-and

Thus, could anybody please advise if there is a way to improve performance of the Allure somehow?
Also it might worth to look the mechanism of generation of the report from DEV perspective, to understand where the time is being lost.

**Comment by baev** [comment]
for such amount of results we suggest migration to Allure EE

**Comment by forrest1g** [comment]
Would you please tell how Allure EE solved the problem? @baev :)

**Comment by BryanGrissomSTOBG** [comment]
The suggestion to migrate to Allure EE is a good recommendation to stay off the product entirely.

**Comment by baev** [comment]
@BryanGrissomSTOBG, that was a nice comment on the closed ticket from 2019! I never push users to use Allure Report or any other products from our team. I believe you should use whatever tool suits you best, and I am happy to do my best to help you find it. 

Regarding the issue topic:

The idea behind Allure is that it behaves as a standalone tool that can be used in any environment without the need to deploy a service or pay for a cloud subscription. It's fully open-source, and you can use it as a baseline for your in-house test reporting solution (or don't ;) ).

Allure Report generates an HTML file from a bunch of results. This works well until you have a lot of data in your reports. For example, simply having 200k tests, you may end up having a 100mb+ JSON file with only test names (so you can navigate through the report). Besides, the report generation may take a while since we need to read 200k+ files from the file system. We did some performance improvements over the years, but we never aimed to support such amounts because even if you generate the report successfully, you still will be fighting the browser and having trouble sharing/storing the reports, etc.

However, we have extensive team experience dealing with such issues. The main one is to optimise test runs, e.g., remove attachments from passed tests and maybe remove some extra steps. 

From an application point of view, pagination is the key. Implementing lazy loading, virtualised lists, and proper state management greatly helps. 

The report generation is tricky. You need to carefully choose between CPU and memory and keep in mind your storage speed. As of today, Allure Report is at least 10 times faster than in 2019. Allure 3 (currently in development) shows some great improvements as well.

But even with all that in mind, you still need to store and share such reports with the team somehow. You can't simply mail 1GB of HTML to stakeholders. You need some centralised storage solution, maybe some advanced rules on what reports to keep and what to remove (and when).

It may not sound that complicated, but from our experience, if you decide to do all that in-house, you will end up having 6 senior engineers working on it full-time. 

 [Allure TestOps](https://qameta.io/) (it used to be called Allure EE back in 2020) is a paid offering by our team that can solve all the problems mentioned and even more. 

At first, it's a service, available as a SAAS and self-hosted. It may process the results in real-time, so even if you have huge amounts of test data, you can start the processing as soon as the first test is finished. So, by the time your test run is complete, most of the data will have been processed and made available in UI.

Second, the UI is designed to support almost any number of tests — customers have over a million tests per run.

Besides, Allure TestOps supports manual testing — you can replace any TMS solution you have with it (and usually save some $$$). 

Finally, the best way to support Allure Report is to consider using Allure TestOps.
